### DISCUSSION TITLE
节点设置成不可拖动，每次点击节点都会触发 node:unselected 事件，请问怎么才能正常点击？

### DISCUSSION THREAD

**Discussion by webpig** [antvis/X6#1856] [Q&A]
节点设置成不可拖动，每次点击节点都会触发 node:unselected 事件，请问怎么才能正常点击？

**Comment by NewByVector** [comment]
正常点击是指什么，是能触发 `node:click` 事件吗？

**Reply by webpig** [reply]
是的，我现在点击节点上面的小组件不会触发点击事件，只触发 node:unselected 事件。

**Reply by NewByVector** [reply]
可以将 selection 的样式修改一下：
```css
.x6-widget-selection-box {
  pointer-events: none;
}
```
