### DISCUSSION TITLE
如何自定义对齐线样式？

### DISCUSSION THREAD

**Discussion by xiazhaohui** [antvis/X6#2250] [Q&A] [answered]
看了文档，要自定义对齐线的样式，可以使用className来配置，但是对齐线的样式是哪一个在起效，比如说我要改变对齐线的颜色为红色，我该怎么写样式？
```javascript
// 对齐线
  snapline: {
    enabled: true,
    className: 'ma-custom-snapline'
  },
```

```less
.ma-custom-snapline {
 // 样式
}
```

**Comment by xiazhaohui** [comment, marked as answer]
找到样式了，自定义类名下边的x6-widget-snapline-horizontal 和x6-widget-snapline-vertical ，修改border-bottom的颜色即可。

```less
.ma-custom-snapline {
  .x6-widget-snapline-horizontal {
    border-bottom: 1px solid #4370FE;
  }
  .x6-widget-snapline-vertical {
    border-right: 1px solid #4370FE;
  }
}
```
