### DISCUSSION TITLE
如何给边添加鼠标悬浮或者选中边的时候，边高亮，以及高亮的颜色如何更改。

### DISCUSSION THREAD

**Discussion by edc-hui** [antvis/X6#3732] [Q&A] [answered]
如题，在文档中没找到设置边鼠标悬浮改变样式的方式，官网图表示例上面的边鼠标悬浮以及选中都有样式，但是看代码就没看到怎么实现的

**Comment by NewByVector** [comment, marked as answer]
两种方案：
1. 使用 css 样式，比如：
```css
.x6-edge:hover {
  path:nth-child(2) {
    stroke: #1890ff;
    stroke-width: 1px;
  }
}

.x6-edge-selected {
  path:nth-child(2) {
    stroke: #1890ff;
    stroke-width: 1.5px !important;
  }
}
```
3. 可以在 `edge:mousenter` 中修改边的样式 ，修改方法参考[文档](http://x6.antv.antgroup.com/tutorial/basic/edge#%E4%BF%AE%E6%94%B9%E8%BE%B9)。
