### ISSUE TITLE
当 SelectionBox 启用时，支持选中被遮盖的节点

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1079]
### Expected Behavior

如果开启了 SelectionBox ，点选父节点显示 SelectionBox 后，区域内的节点就不能被选中，除非先点击空白区域取消选中状态，移除 SelectionBox 。
期望的行为是开启 SelectionBox 并不影响点选节点。

### Possible Solution

监听 SelectionBox 的 click 事件，获取点击位置处的最外层节点，如果同时开启了 selection ，那么选中该节点。

### Additional Context

https://user-images.githubusercontent.com/36734012/121460556-b1095180-c9df-11eb-8644-c2e72a81d64f.mov

**Comment by OpportunityLiu** [comment]
反正我是直接 
```css
.x6-widget-selection-box {
  pointer-events: none;
}
```
了事的，我也不用 `"box:*"` 事件

**Comment by tiancihe** [comment]
> 反正我是直接
> 
> ```css
> .x6-widget-selection-box {
>   pointer-events: none;
> }
> ```
> 
> 了事的，我也不用 `"box:*"` 事件

这样就失去了 SelectionBox 拖拽节点的能力了，直接操作会拖拽其内部的节点

**Comment by OpportunityLiu** [comment]
所以你的意思是点击的时候能穿透，拖拽的时候又要不穿透？

**Comment by tiancihe** [comment]
> 所以你的意思是点击的时候能穿透，拖拽的时候又要不穿透？

嗯，是这个意思

**Comment by NewByVector** [comment]
可以这样解决：
1. 增加下面样式
```css
.x6-widget-selection-box {
  pointer-events: none;
}
```
2. 设置 `stopDelegateOnDragging` 为 `false`
```ts
const graph = new Graph({
  interacting: {
    stopDelegateOnDragging: false
  }
})
```
demo：https://codesandbox.io/s/selection-child-sezj3
