### ISSUE TITLE
节点在选中状态下移动不会触发node:move、node:moved事件

### ISSUE THREAD

**Issue by SingleShadow** [antvis/X6#1159]
### Steps To Reproduce

https://codesandbox.io/s/undo-del-forked-6z851

1. 未选中节点直接移动，可以正常执行node:move、node:moved
2. 选中节点移动，不能执行node:move、node:moved
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
可以设置样式：
```css
.x6-widget-selection-box{
  pointer-events: none;
}
```
