### ISSUE TITLE
节点选中状态下不会触发鼠标移入移出事件

### ISSUE THREAD

**Issue by huangkaibo** [antvis/X6#1199]
https://codesandbox.io/s/practical-hooks-t9zbk?file=/src/app.tsx

控制台打印了 鼠标移入移出节点的信息
先选中一个节点, 鼠标再移入移出, 会发现没触发事件
其他未选中的节点没这个问题

**Comment by NewByVector** [comment]
是因为节点上方盖了一层,可以设置 
```css
.x6-widget-selection-box {
  pointer-events: none;
}
```
