### ISSUE TITLE
使用Stencil，如何禁止节点拖拽

### ISSUE THREAD

**Issue by qq382724935** [antvis/X6#1280]
在某些业务下，需要动态设置Stencil中的组件可否进行拖拽，考虑增加diabled api或有其它好的解决建议吗？

**Comment by NewByVector** [comment]
现在还不支持的，可以通过控制样式来实现你的功能。
```css
.x6-widget-stencil-group-content {
  pointer-events: none;
}
```
