### ISSUE TITLE
请教一下, 选中节点的情况下,怎么点击节点内的内容?

### ISSUE THREAD

**Issue by cheng-xiaofeng** [antvis/X6#1508]
如图1, 选中节点, 依然可以点击id
而图2, 选中节点, 就不能点击id,
我想要做到图一这种样子

![image](https://user-images.githubusercontent.com/33592850/140279103-25bbcab1-25dd-4b3d-bdfa-b348efc6c664.png)
![image](https://user-images.githubusercontent.com/33592850/140279183-5b0ee1c6-0365-4936-8683-da6239a799bf.png)

**Comment by NewByVector** [comment]
可以修改样式：
```css
.x6-widget-selection-box-node {
  pointer-events: none
}
```
