### ISSUE TITLE
想适应暗色主题，能把小地图的颜色改成黑色吗？

### ISSUE THREAD

**Issue by rxdrag** [antvis/X6#1942]
### 功能描述

画布的背景弄成黑色了，但是小地图的颜色还是白，怎么弄啊？

### 期望解决方案

希望可以修改小地图的颜色

**Comment by NewByVector** [comment]
可以使用样式来解决：
```css
.x6-widget-minimap .x6-graph-background {
  background-color: #000
}
```
