### ISSUE TITLE
链接桩 连线时使用的是 cursor: crosshair，出现十字架连接，能否使用自定义图标

### ISSUE THREAD

**Issue by itwmike** [antvis/X6#2180]
### 功能描述

![3715187f609d464e26e95399c4066f0](https://user-images.githubusercontent.com/6613191/171610707-09b35a45-e062-48b6-96ea-a1f08664c8f2.png)

十字架能不能使用自定义图标？

### 期望解决方案

增加自定义能力

**Comment by NewByVector** [comment]
改这个 css 样式就可以了
```css
.x6-node [magnet='true'] {
  cursor: crosshair;
}
```
