### ISSUE TITLE
How to config to fitIntoView effect

### ISSUE THREAD

**Issue by liuyuchenzh** [antvis/X6#338]
Or in CSS analogy

```css
element {
  object-fit: contain;
}
```

**Comment by bubkoo** [comment]
@liuyuchenzh 是想要缩放画布内容，使画布内容填充满视口吗？

**Comment by liuyuchenzh** [comment]
@bubkoo Basically yes.

Scale the canvas (or should I refer to graph?) to perfectly fit into the container (the HTMLElement).

In both *scale up* or *scale down* direction given the size of container and canvas.

**Comment by bubkoo** [comment]
@bubkoo You can try [`graph.scaleContentToFit(...)`](https://x6.antv.vision/zh/docs/api/graph#scalecontenttofit).

**Comment by liuyuchenzh** [comment]
Hmmm.

Maybe I am not configuring the options properly?

Tried `contentArea`, `viewportArea ` and `preserveAspectRatio `, none of them worked.

To put it into a more concrete context.

I have a canvas with size

```css
canvas {
  width: 1000px;
  height: 800px;
}
```

And the container is like

```css
container {
  width: 1000px;
  height: 600px;
}
```

Somehow the bottom of the canvas is always chopped  from the container.
![x6](https://user-images.githubusercontent.com/12220475/100402786-20e56980-3098-11eb-96a8-f8e7f3fa775a.png)
