### ISSUE TITLE
画布滚动条问题，当节点靠近画布边缘时，线显示不全

### ISSUE THREAD

**Issue by zq8024** [antvis/X6#3642]
### 问题描述

画布滚动条问题，当节点靠近画布边缘时，线显示不全

### 重现链接

https://codesandbox.io/s/zen-thunder-0rrowu?file=/src/App.js

### 重现步骤

进入页面就可以看到左边的线显示不全
![line1](https://github.com/antvis/X6/assets/68761/436a84c2-ca72-4fb7-b688-40065bd73702)

### 预期行为

希望线可以完全显示
![line2](https://github.com/antvis/X6/assets/68761/5efe34ec-909e-46aa-a98b-651761d52c82)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- X6 版本: [1.28.2 ... ]

**Comment by OpportunityLiu** [comment]
计算 BBOX 的问题，我们是用
```css
.x6-graph > .x6-graph-svg {
  overflow: visible;
}
```
凑合的，感觉也够用了

**Comment by oyal** [comment]
> 计算 BBOX 的问题，我们是用
> 
> ```css
> .x6-graph > .x6-graph-svg {
>   overflow: visible;
> }
> ```
> 
> 凑合的，感觉也够用了

用了滚动插件，这个样式不起作用

**Comment by OpportunityLiu** [comment]
![image](https://github.com/antvis/X6/assets/13471233/ab8a6bc4-0cdd-48a2-b560-e35a142ab857)
再加上
```css
.x6-graph {
  overflow: visible;
}
```
