### ISSUE TITLE
dnd拖拽时，希望支持触发监听的画布事件

### ISSUE THREAD

**Issue by csgajcr** [antvis/X6#4184]
### 功能描述

想实现一个功能，dnd拖入的节点，拖到连线上时，自动添加到该连线上。
但目前通过 plugin-dnd 拖入节点时，画布接受不到任何事件，导致此功能无法实现。
看了 dnd 的源码，发现 dnd 在 body 新建一个层，里面放了一个虚拟画布，在里面实现的逻辑。

### 期望解决方案

1. 当前版本是否有其他曲线的方式能够实现上述效果
2. 希望未来 dnd 能支持选项是否触发画布事件

**Comment by csgajcr** [comment]
问题已解决，覆盖组件原有样式即可。
```css
.x6-widget-dnd {
  pointer-events: none!important;

  &.dragging {
    display: inline-block;
  }

  &.dragging * {
    pointer-events: none !important;
  }
}
```
