### ISSUE TITLE
群组里父node选中之后，子node无法被拖动或选中

### ISSUE THREAD

**Issue by eschervr-dev** [antvis/X6#518]
### Expected Behavior

群组里面，如果graph加了selecting，选中父node之后里面的子node就没法拖动了 ，也无法被选中

![0FB7BB4C-F557-4C42-B2FC-A8840F8893EC](https://user-images.githubusercontent.com/55189592/103868650-1e007e80-5104-11eb-999b-f11e14e24173.png)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by NewByVector** [comment]
代码中增加样式
```css
.x6-widget-selection-selected {
    pointer-events: none;
}
```
